backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: static/images/
public_folder: /images/
collections:
  - label: "Posts"
    name: "post"
    folder: "content/post/{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "URL", name: "slug", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "select", multiple: true, options: ["Design", "UX", "Dev"], allow_add: false}
      - {label: "Categorias", name: "categories", multiple: true, options: ["Design", "UX", "Dev"]}               
      - {label: "Conteúdo", name: "body", widget: "markdown"}