backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: static/images/
public_folder: /images/
locale: 'pt'
collections:
  - label: "Post"
    name: "post"
    folder: "content/post"
    create: true
    fields:
      - {label: "Data", name: "date", widget: "date"}    
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "string"]}
      - {label: "Imagem", name: "image", widget: "image"}         
      - {label: "Conteúdo", name: "body", widget: "markdown"}
      
